### ISSUE TITLE
core:copy in wrong spot

### ISSUE THREAD

**Issue by andyleejordan** [mndrix/atom-emacs-core-keys#2]
Should be:

```
'body':
    'alt-w': 'core:copy'
```

Not under `atom-text-editor` because then you can't copy out of the settings pane (or any non-editors).

For some reason this package also breaks using `cmd-c` in non-editors.

We should review all other keybindings that may be misplaced as well.

**Comment by mndrix** [comment]
I'm not able to reproduce this.  I can use `alt-w` and `cmd-c` to copy from all the places you mentioned.  What do you see when you turn on Atom's keybinding resolver?  Which version of Atom are you using?

**Comment by andyleejordan** [comment]
I'm on OS X 10.10.3 with Atom 0.198.0. What do you mean by:

> What do you see when you turn on Atom's keybinding resolver?

I installed the emacs-core-keys package (and no other keybinding packages) and left it enabled (Atom has certainly be restarted as well).

**Comment by andyleejordan** [comment]
I just doubled checked, with `emacs-core-keys` as the only enabled community package, the problem persists.

`core:copy` definitely belongs under `body` as the `cmd-c` binding from the `Core` source puts it under the `body` selector.

**Comment by mndrix** [comment]
> What do you mean by:
> 
> > What do you see when you turn on Atom's keybinding resolver?

Open the command palette, type "key binding resolver" and press enter. You'll see a "Key Binding Resolver" panel open at the bottom of your editor.  Each time you press a keyboard shortcut, it shows which command is being triggered, which selectors apply and which package provided the keybinding.

> core:copy definitely belongs under body as the cmd-c binding from the Core source puts it under the body selector.

I don't mind moving the keybinding, but I want to be sure we fix the `cmd-c` breakage you've experienced.  If I can't reproduce the problem, I can't be confident of the fix.

**Comment by andyleejordan** [comment]
Ah! That is what I've been needing to debug this, thank you.

The resolver shows `cmd` being pressed, but does not register the subsequent `c` (and I made sure to know what it should look like by seeing `cmd-c` resolve to `core:copy` in an editor), and does not copy.

However, _strangely_, `atom --safe` exhibits the first part of the behavior, the resolver only shows `cmd` when copying from a settings window, but `cmd-c` does copy.

**Comment by andyleejordan** [comment]
Now interestingly, completely reinstalling Atom has fixed the usage of `cmd-c` in non-editors with this package, but the resolver still does not show anything past the initial press of `cmd`.

**Comment by mndrix** [comment]
> completely reinstalling Atom has fixed the usage of cmd-c in non-editors

That's good to hear.

> the resolver still does not show anything past the initial press of cmd

That's odd.  Since you get the same behavior with `atom --safe` I assume this has something to do with Atom rather than the emacs-core-keys package.

Anyway, I'll merge your pull request now that we understand `cmd-c`.  Thanks for debugging this.

**Comment by andyleejordan** [comment]
Yes, definitely something odd in Atom. I'm tempted to go open a bug report.

Thanks for the merge!
